name: CI Pipeline

on:
  push:
    branches: [ main, desenvolvimento, features ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar os testes
        run: python -m pytest

      - name: Executar a aplicação
        run: python app/app.py
